name: Build, Test and Deploy the YATT iOS App

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: macos-latest
        
    steps:
      - uses: actions/checkout@v4
            
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

      - name: Run Unit Tests with Coverage
        run: |
          xcodebuild test \
            -project IOS-APP_ASE2.xcodeproj \
            -scheme IOS-APP_ASE2 \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            -enableCodeCoverage YES
            
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult

  build:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

      - name: Build App
        run: |
          xcodebuild clean archive \
            -project IOS-APP_ASE2.xcodeproj \
            -scheme IOS-APP_ASE2 \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/IOS-APP_ASE2.xcarchive
